# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_convert_time
#'
#' @noRd
rcpp_convert_time <- function(hms) {
    .Call(`_gtfsrouter_rcpp_convert_time`, hms)
}

#' rcpp_time_to_seconds
#'
#' Vectorize the above function
#'
#' @noRd
rcpp_time_to_seconds <- function(times) {
    .Call(`_gtfsrouter_rcpp_time_to_seconds`, times)
}

#' rcpp_make_timetable
#'
#' Make timetable from GTFS stop_times
#'
#' @noRd
rcpp_make_timetable <- function(stop_times) {
    .Call(`_gtfsrouter_rcpp_make_timetable`, stop_times)
}

#' rcpp_csa
#'
#' Connection Scan Algorithm for GTFS data. The timetable has 
#' [deparutre_station, arrival_station, departure_time, arrival_time,
#'     trip_id],
#' with all entries as integer values, including times in seconds after
#' 00:00:00. The station and trip IDs can be mapped back on to actual station
#' IDs, but do not necessarily form a single set of unit-interval values
#' because the timetable is first cut down to only that portion after the
#' desired start time.
#'
#' @noRd
rcpp_csa <- function(timetable, transfers, nstations, ntrips, start_stations, end_stations, start_time) {
    .Call(`_gtfsrouter_rcpp_csa`, timetable, transfers, nstations, ntrips, start_stations, end_stations, start_time)
}

